#!/bin/bash
#
docker run -d \
  --name=transmission \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/Vilnius \
  -e TRANSMISSION_WEB_HOME=/flood-for-transmission/ `#optional` \
  -e USER=karl `#optional` \
  -e PASS=Konul.karl `#optional` \
  -p 9091:9091 \
  -p 51413:51413 \
  -p 51413:51413/udp \
  -v transmission:/config \
  -v /media/downloads:/downloads \
  -v /media/movies:/movies \
  --restart unless-stopped \
  lscr.io/linuxserver/transmission:latest
