#!/bin/bash

#creates all the variables so its easy to modify 
date_log=$( date +%d%m%Y-%H%M )
path_log="$HOME/.scripts/activated/file-backups/logs"
rsync_name_log="rsync-$date_log"
rsync_error_log="error-rsync-$date_log"
tar_name_log="tar-$date_log"
tar_error_log="error-tar-$date_log"

#creates the path_log variable if it doesnt exist
[ -d $path_log ] || mkdir -p $path_log

#creates the backups
$HOME/.scripts/activated/file-backups/tarball > $path-log/$tar-name-log 2> $path-log/$tar-error-log & $HOME/.scripts/activated/file-backups/rsync &> $path-log/$rsync-name-log 2> $path-log/$rsync-error-log

#clear all the log files thats older than 1 month
$HOME/.scripts/activated/file-backups/clear-log

