#!/bin/bash

#This script is for making tarballs 
#You can run this script with the main script in order to both make tar and rsync backups

#DATE format
date_for_backup=$(date +%d-%h-%Y-%H-%M )  

#Reads my dmenu script and backup all config files from it
dmenu_conf_files=$(sed -n '/declare/,/)/p' ~/.dmenu/dm-editconfig | grep -v ^declare | sed -e 's/"//g' -e '/)/d' -e '/^$/d' | grep -v "#" | grep -v if | awk -F "=" '{print $NF}' | sed -e "s|\$HOME|$HOME|g" )

#location to store the backups
backuplocation="$HOME/Yandex.Disk/Tars"

#Creates the array add the folders you want to backup here
declare -a options=(

$dmenu_conf_files
$HOME/.zsh_history
$HOME/Videos/Kdenlive/Projects/
$HOME/.local/share/applications/
$HOME/.password-store

)


for opt in $(printf '%s\n' "${options[@]}") ; do


   [ -e $opt ] && options_new="$opt $options_new"


done


files_to_backup=$(printf '%s\n' "${options_new[@]}")
 

[ -d $backuplocation ] || mkdir -p $backuplocation

tar -zcpvf $backuplocation/configfiles-$date_for_backup.tgz $files_to_backup


#This will remove old tar backups
#Modiy these variables to fit your needs

backups=$( ls -A $backuplocation/ | wc -l )


#Modify this if you want to save more or less backups
#for example now it will delete the oldest backup if there is more than 7
while [ $backups -gt "15" ] ; do

   rmbak=$( ls -At $backuplocation/* | tail -n1 )

   rm -f $rmbak  

   backups=$( expr $backups - 1 )

done
