#!/bin/bash



current=$(cat /sys/class/leds/asus::kbd_backlight/brightness )


decrease=$( expr $current - 1 )

[ $current -gt "0" ] && echo $decrease > /sys/class/leds/asus::kbd_backlight/brightness   
