#!/bin/bash
###____  _                      _      
#|  _ \| |__   ___   ___ _ __ (_)_  __
#| |_) | '_ \ / _ \ / _ \ '_ \| \ \/ /
#|  __/| | | | (_) |  __/ | | | |>  < 
#|_|   |_| |_|\___/ \___|_| |_|_/_/\_\
#                                     
# -*- coding: utf-8 -*-
#Script to set random bg for a wayland session

#Sets the directory that the script will look in
declare -a options=(

"$HOME/Pictures/Wallpapers"
"$HOME/Pictures/nord"
"$HOME/Pictures/Nature"


)

killall swaybg

#Will pick a random directory from the array
RANDOM_DIR=$(printf '%s\n' "${options[@]}" | shuf | head -n1)

#Will pick a random picture from that directory
RANDOM_PICTURE=$(ls -d $RANDOM_DIR/* | shuf | head -n1)

#Sets the background
swaybg -i $RANDOM_PICTURE &

IMAGE=$(cat ~/.fehbg | awk '{print $NF}' | tail -n1)  


sed -i "s|$IMAGE|$RANDOM_PICTURE|g" ~/.fehbg
