#!/usr/bin/fish 

#This will choose a random bacground for you
#just change the path to fit your needs

set pic (ls $HOME/Pictures/Wallpapers )
set choose (echo $pic | xargs -n1 | shuf -n1)   

feh  --bg-fill "$HOME/Pictures/Wallpapers/$choose"

sudo cp "$HOME/Pictures/$choose"  
