#!/bin/bash
###____  _                      _      
#|  _ \| |__   ___   ___ _ __ (_)_  __
#| |_) | '_ \ / _ \ / _ \ '_ \| \ \/ /
#|  __/| | | | (_) |  __/ | | | |>  < 
#|_|   |_| |_|\___/ \___|_| |_|_/_/\_\
#                                     
# -*- coding: utf-8 -*-

#Script that will lock a wayland session using swaylock
image=$(cat ~/.fehbg | grep feh | awk '{print $NF}')

swaylock -i $image
