#!/bin/bash
###____  _                      _      
#|  _ \| |__   ___   ___ _ __ (_)_  __
#| |_) | '_ \ / _ \ / _ \ '_ \| \ \/ /
#|  __/| | | | (_) |  __/ | | | |>  < 
#|_|   |_| |_|\___/ \___|_| |_|_/_/\_\
#                                     
# -*- coding: utf-8 -*-
#Script to set the background for hyprland

killall swaybg 

PICTURE=$(cat $HOME/.fehbg | grep feh | awk '{print $NF}')

swaybg -i $PICTURE
