format = """
[\uE0B6](fg:#DF9B8B)[$directory](bg:#DF9B8B)[\uE0B0](fg:#DF9B8B bg:#EAA9A2)$git_branch[\uE0B0](fg:#EAA9A2 bg:#EBBCBA)$git_status[\uE0B0](#EBBCBA bg:#F2C1B7)$time[\uE0B0](#F2C1B7 bg:none) $all$character """

add_newline = true

[directory]
style = "bg:#DF9B8B fg:#191724"

[git_branch]
format = "[ $symbol$branch ]($style)"
style = "bg:#EAA9A2 fg:#191724"

[git_status]
format = "[ $all_status$ahead_behind ]($style)"
style = "bg:#EBBCBA fg:#191724"

[time]
disabled = false
format = "[ $time ]($style)"
style = "bg:#F2C1B7 fg:#191724"
