[theme]
background = "black"
primary = "#FFFACD"
secondary = "#81A1C1"
title = "#81A1C1"
playing = "#81A1C1"
playing_selected = "black"
playing_bg = "#2E3440"
highlight = "#FFFACD"
highlight_bg = "#81A1C1"
error = "#FFFACD"
error_bg = "#BF616A"
statusbar = "#2E3440"
statusbar_progress = "#81A1C1"
statusbar_bg = "#81A1C1"
cmdline = "#FFFACD"
cmdline_bg = "#2E3440"
search_match = "#BF616A"
