#!/bin/bash

#Script that easily makes a backup of a subvolume to another btrfs drive
snapshot_this="$1"
snapshot_name="$1-snap_$(date +%d%m%Y-%H%M)"
send_to="$2"


sudo btrfs subvolume snapshot $snapshot_this $snapshot_name
sudo btrfs property set $snapshot_name ro true
sudo btrfs send $snapshot_name | sudo btrfs receive $send_to
sudo btrfs property set $snapshot_name ro false
sudo rm -rf $snapshot_name
